services:
  model-service:
    build:
      context: .
      args:
        MAIN_CLASS: ch.tichess.services.ModelServer
    container_name: tichess-model-service
    environment:
      MODEL_SERVICE_PORT: 8081
    ports:
      - "8081:8081"

  controller-service:
    build:
      context: .
      args:
        MAIN_CLASS: ch.tichess.services.ControllerServer
    container_name: tichess-controller-service
    depends_on:
      - model-service
      - postgres-db
      - mongo-db
    environment:
      CONTROLLER_SERVICE_PORT: 8082
      MODEL_SERVICE_URL: http://model-service:8081
      DB_TYPE: mongo
      MONGO_URI: mongodb://mongo-db:27017
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: tichess
    ports:
      - "8082:8082"

  postgres-db:
    image: postgres:15-alpine
    container_name: tichess-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tichess
    ports:
      - "5432:5432"

  mongo-db:
    image: mongo:6.0
    container_name: tichess-mongo-db
    ports:
      - "27017:27017"

  view-service:
    build:
      context: .
      args:
        MAIN_CLASS: ch.tichess.view.RestServer
    container_name: tichess-view-service
    depends_on:
      - controller-service
    environment:
      VIEW_SERVICE_PORT: 8080
      CONTROLLER_SERVICE_URL: http://controller-service:8082
    ports:
      - "8080:8080"
